### PR TITLE
Bump shared data services to latest version

### PR DESCRIPTION
**Pull request by ANeumann82**
This bumps the shared data services tools to latest version

Why:
Shared Data Services now (optionally) include a local metadata.sh to allow customization of DS_KUDO_VERSION for example for PR-Builds

**When this is merged, it requires an update to the TC configuration**

The `./deploy-kudo-controller-and-crds.sh` is now named `deploy-kudo.sh`

Signed-off-by: Andreas Neumann <aneumann@mesosphere.com>

### CODE REVIEW

**Comment by alembiewski** [comment]
@ANeumann82, it seems like CI is constantly failing. Given, that it is becoming a blocker, could you please take a look into CI and check if it's related to changes?

**Comment by alembiewski** [comment]
Fixed the CI by bumping Konvoy to `v1.2.4`, all the tests passed successfully.

**Comment by ANeumann82** [comment]
@alembiewski Thanks for fixing CI, and sorry for keeping that over the weekend.

**Comment by alembiewski** [comment]
@ANeumann82, no worries, and thank you for the update!

**Pull request merged**
