### PR TITLE
[DCOS-59168] grafana dashboard

### PR DESCRIPTION
**Pull request by VladimirKravtsov**
The PR addresses Spark Operator and Application monitoring dashboards. Which based on metrics scraped by Prometheus from Spark Operator, Driver and Executors, ran in Kubernetes cluster.

### How to verify
1) Spin up Konvoy cluster
2) Follow instruction in [README.md](https://github.com/mesosphere/kudo-spark-operator/tree/DCOS-59168_Grafana_dashboard#submitting-spark-application) to deploy Spark Operator and application example.
3) Go to Grafana and press + then select Import
4) Copy the dashboard code from [grafana_spark_operator](https://github.com/mesosphere/kudo-spark-operator/blob/DCOS-59168_Grafana_dashboard/grafana/grafana_spark_operator.json) and paste it to text area in Grafana
5) Save and select the "Spark Operator" dashboard to play around.

And repeat steps 3 - 5 for  [spark_application_dashboard.json](https://github.com/mesosphere/kudo-spark-operator/blob/DCOS-59168_Grafana_dashboard/grafana/spark_application_dashboard.json)  if you want check the Spark Driver and Executors metrics dashboard.

Find a couple of screenshots here Spark Driver and Executors metrics:
Screen Shot 2019-10-01 at 02 13 05
Screen Shot 2019-10-01 at 02 14 29
Screen Shot 2019-10-01 at 02 14 55
Screen Shot 2019-10-01 at 02 15 15
Screen Shot 2019-10-01 at 02 15 38
Screen Shot 2019-10-01 at 02 15 53
Screen Shot 2019-10-01 at 02 16 24
Screen Shot 2019-10-01 at 02 16 53

### CODE REVIEW

**Comment by VladimirKravtsov** [comment]
@akirillov the links are fixed, thanks for catch it. Regarding to the dashboard - yes, it's my misunderstanding. I re-read ticket and there is clearly described the goal. Maybe I have started progress the ticket was created, just after discussion. 
Anyway, do we keep the Spark application related metrics dashboard or it should get rid? WDYT?

**Comment by akirillov** [comment]
> Anyway, do we keep the Spark application-related metrics dashboard or it should get rid? WDYT?

Application-level metrics are definitely important and there's no reason we should remove this dashboard -  thanks for implementing that. Out of curiosity, is this dashboard based on the one we've built for DCOS Spark?

Also, can you please put dashboards under `dashboards` instead of `grafana` to make it more generic?

**Comment by VladimirKravtsov** [comment]
Hi @akirillov 
> Application-level metrics are definitely important and there's no reason we should remove this dashboard - thanks for implementing that. Out of curiosity, is this dashboard based on the one we've built for DCOS Spark?

It has been made from scratch.

**Comment by VladimirKravtsov** [comment]
> Also, can you please put dashboards under dashboards instead of grafana to make it more generic?

Perhaps, it make sense. Renamed

**Comment by VladimirKravtsov** [comment]
Ready to review

**Comment by VladimirKravtsov** [comment]
Thanks for the review, @akirillov!

**Pull request merged**
